language: python

python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
- '3.6'

matrix:
  include:
    - python: 3.7
      dist: xenial

install:
- pip install -r test_requirements.txt

script:
- flake8
- python setup.py coverage
