language: python

python:
- '2.7'
#  -  # flake8 crashes! '3.3'
- '3.4'
- '3.5'
- '3.6'

matrix:
  include:
    - python: 3.7
      dist: xenial

install:
- pip install -r requirements.txt
- pip install -r test_requirements.txt

script:
- flake8 cfgs.py test
- mypy cfgs.py
- pytest test

# Don't compile "experimental" branches starting with x-, y-, or z-.
branches:
  except:
    - /^x-.*$/
    - /^y-.*$/
    - /^z-.*$/
